---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ibmqo
  name: ibmqo
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    tier: ibmqo
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Route
metadata:
  name: ibmqo
spec:
  to:
    kind: Service
    name: ibmqo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibmqo
  labels:
spec:
  selector:
    matchLabels:
      tier: ibmqo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: ibmqo
    spec:
      containers:
        - image: singhp11/ibmq_crd:latest
          name: ibmqo
          env:
            - name: AWS_ACCESS_KEY_ID
              value: 
            - name: AWS_SECRET_ACCESS_KEY
              value: 
          ports:
            - containerPort: 5000
              name: ibmqo

